ALTER TABLE tasks
  ADD COLUMN IF NOT EXISTS week VARCHAR(20) DEFAULT '',
  ADD COLUMN IF NOT EXISTS deliverable TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS definition_of_done TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS dependencies TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS risk TEXT DEFAULT '';
